spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:C:/Shubhajit_local/code/data/sample
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui

server:
  port: 8082

logging:
  level:
    org:
      springframework: info

management:
  enpoints:
    health:
      group:
        custom:
          show-components: always
          show-details: always
          include: diskSpace,ping

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method