DROP TABLE IF EXISTS T_ENTERPRISE_APPLICATION;
CREATE TABLE T_ENTERPRISE_APPLICATION (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    APP_ID VARCHAR(50) NOT NULL,
    APP_NAME VARCHAR(100) NOT NULL,
    APP_URL VARCHAR(500) NOT NULL,
    APP_AUTH_TYPE VARCHAR(50),
    APP_UP_STREAM VARCHAR(100),
    APP_DOWN_STREAM VARCHAR(100)
);